### ISSUE TITLE
Remove ODU Logo/Any reference to computer science

### ISSUE THREAD

**Issue by bagel-dawg** [bagel-dawg/accounts#15]
Many html assets have odu memorabilia that needs to be replaced with generic images. Even better: Custom images that can be uploaded through the admin or otherwise changed.

TODO:

- [x] Forms contain "CS" in the labels

- [x] CS Logo is the default image

- [x] "CS Account Management" -> "Account Management"

- [x] Replace support email in base.html/footer. Held up by issue #24 

- [x] Replace company name. Held up by issue #24

- [x] Replace company webpage. Held up by issue #24

**Comment by bagel-dawg** [comment]
TODO:

- [ ] Replace support email in base.html/footer. Held up by issue #24 

- [ ] Replace company name. Held up by issue #24

- [ ] Replace company webpage. Held up by issue #24

**Comment by bagel-dawg** [comment]
This can be closed out with the merging of PR #31
